version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: meu-app-nextjs-compose
    container_name: meu-nextjs-container
    ports:
      - "3000:3000"
    restart: unless-stopped